[package]
name = "raspberrypi-temperature-rust"
version = "0.1.0"
authors = ["Cristian Rojas <injcristianrojas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dotenv = "0.15.0"
openssl = { version = "0.10.29", features = ["vendored"] }
reqwest = { version = "0.10", features = ["blocking", "json"] }
rocket = "0.4.6"
rusqlite = "0.24.2"
schedule_recv = "0.1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
w1_therm_reader = "0.1.0"
pwr-hd44780 = "0.1.3"

[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["handlebars_templates", "json", "serve"]